name: Test Node Workflow

on: 
  push:
    branches:
      - main

jobs: 
  build: 
    name: Build with Node
    runs-on: ubuntu-latest

    container: 
      image: node:20.12.2

    steps: 
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Display Node.js Version
      run: node --version

    - name: Display npm Version
      run: npm --version

    - name: Install Dependencies
      run: npm install
