name: Test Node with workflow 
on: push 
jobs: 
  first-job: 
    name: Build with Node 
    runs-on: ubuntu-latest
    container: node:20.12.2
    steps: 
    - run: node --version
    - run: npm --version
    - uses: actions/checkout@v2
    - run: npm install 